#!/bin/bash

## Install patternlab, some plugins, starterkit, set some config options and link patterns and css to drupal theme.
##
## Usage: fin patternlab-install

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SRC_PATH="${PROJECT_ROOT}/src"
THEMES_PATH="$SRC_PATH/themes"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
VENDOR_PATH="${PROJECT_ROOT}/vendor"
CONFIG_PATH="${PROJECT_ROOT}/config"


#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper functions --------------------------------

cd $PROJECT_ROOT

echo
echo -n "Which theme do you want to install patternlab? "
read name

THEME_PATH="$THEMES_PATH/$name"
PATTERNLAB_PATH="$THEME_PATH/patternlab"

if [ ! -d "$THEME_PATH" ]; then
   echo "theme does not exist, quitting"
   exit 1
fi

cd $THEME_PATH

echo ""
echo "Installing to $THEME_PATH/patternlab"
echo ""

/usr/bin/expect -c "
  set timeout 3600
  spawn -noecho composer create-project drupal-pattern-lab/edition-twig-standard patternlab
  expect \"choose an option or hit return to skip:\"
  send \"\r\"
  interact
"
cd patternlab

php core/console -c --set twigAutoescape=0
echo ""

echo-green "Installing data transform plugin and drupal twig components"
composer require aleksip/plugin-data-transform pattern-lab/drupal-twig-components
echo ""

echo-green "Installing drupal minimal starterkit"
echo ""
php core/console --starterkit --install pattern-lab/starterkit-twig-drupal-minimal

cd source/css
curl -O https://raw.githubusercontent.com/pattern-lab/starterkit-twig-base/master/dist/css/pattern-scaffolding.css
cd ../../
echo ""

sed -i '.bak' -e '/style.css/a \
<link rel="stylesheet" href="../../css/pattern-scaffolding.css?{{ cacheBuster }}" media="all" /> \
' source/_meta/_00-head.twig
echo-green "Added pattern-scaffolding.css file and link tag in patternlab/source/_meta/_00-head.twig"

echo ""
sed -i '.bak' "s:../../css/style.css:../../../../css/style.css:g" source/_meta/_00-head.twig
echo-green "Set patternlab css path to use theme css in patternlab/source/_meta/_00-head.twig saved backup to patternlab/source/_meta/_00-head.twig.bak"
echo ""

cd ..
fin exec php patternlab/core/console --generate

echo ""
cd templates

ln -s ../patternlab/source/_patterns/ patterns
echo-green "Linked patternlab _patterns dir to theme/templates/patterns"
echo ""

echo "Install done, some helpful patternlab commands:"
echo ""
echo "To compile patternlab:"
echo "fin patternlab-generate or fin patternlab-generate themename"
echo ""
echo "To watch patternlab files for changes and compile:"
echo "fin patternlab-watch of fin patternlab-watch themename"
echo ""
echo "To start a server to view patternlab:"
echo "cd src/themes/THEMENAME/patternlab"
echo "php core/console --server"
echo "Or just open patternlab/public/index.html in your browser"
echo ""



